### ISSUE TITLE
CLI cannot be installed (bucket was deleted)

### ISSUE THREAD

**Issue by mauricejk** [GoogleCloudPlatform/gcping#28]
! curl https://storage.googleapis.com/gcping-release/gcping_linux_amd64_0.0.3 > gcping && chmod +x gcping

is broken as the project associated with the bucket was deleted.

./gcping: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>ProjectNotFound</Code><Message>The requested project was not found.</Message><Details>The requested project was not found.</Details></Error>'

**Comment by fabiopedrosa** [comment]
Same. Any repo maintainer can look into it?

**Comment by jcvasquezbetancur** [comment]
oh no, same issue here. yet unassigned?

**Comment by samtstern** [comment]
@rakyll @ImJasonH anything we can do about this?

**Comment by ImJasonH** [comment]
I can't speak for @rakyll, but I do know that neither of us work for Google anymore, so we might need to rely on other contributors to keep this project moving forward. 

As for this specific issue, I would guess that the bucket was deleted because it was owned by a googler who left, and Google deleted the project. If someone wants to contribute a goreleaser config that publishes built binaries to GitHub Releases that could be cool. I'd be happy to help if someone steps up.

Beyond that there's also the issue that even if you can install the binary, it'll hit endpoints that don't exist anymore since I migrated https://gcping.com to Cloud Run. #29 should fix that. #27 too.

GCPing, both the website and the CLI, were always side projects, and now that neither of us work at Google I suspect they're even side-ier than ever. If anybody finds them useful and wants to contribute, now would be a great time. 😄

**Comment by samtstern** [comment]
@ImJasonH thanks for the thoughtful response! Didn't realize this was all Xooglers :-)

**Comment by mastersingh24** [comment]
@ImJasonH  - I'd be interested in maintaining this project.  I've found this to be a useful utility for sure.   Who are the active maintainers?

**Comment by imjasonh** [comment]
@mastersingh24 for _this repo_ ([gcp/gcping](https://github.com/googlecloudplatform/gcping), the CLI), I don't know if there are any active maintainers.

For [imjasonh/gcping](https://github.com/imjasonh/gcping), the website https://gcping.com, I'm the only active maintainer, in whatever free time I can find to maintain it.

I'd be more than happy to take on anybody interested in running releases of imjasonh/gcping, it's fairly straightforward. I'd be especially interested in anybody current Google employees want to take over ownership of the infrastructure. It costs about $18/month to run the global load balancer. 💸

**Comment by samtstern** [comment]
@imjasonh I'd be happy to migrate this project into the google.com org (if it isn't already) so that I can cover the load balancer bill with internal billing. However I wouldn't be comfortable with an external maintainer having total access to a project with internal billing.

Would the maintainer need access to the project with the load balancer?

**Comment by imjasonh** [comment]
@samtstern Thanks. Yeah, I think google's org policy would prevent a non-googler from doing that anyway, at least without lots of approval headaches.

I don't think I'd _need_ access to the project, but not having access would make me a pretty bad co-maintainer 😆 , so you'd probably end up taking it all on yourself (or you along with other googler owners like @mastersingh24). If you're fine with that, I'm fine with that.

**Comment by mastersingh24** [comment]
I'd be happy to help take this on/over as well @imjasonh @samtstern

**Comment by enocom** [comment]
A group of people at Google have taken over this project. The release bucket is available again for v0.0.5 and onward.

Thanks to everyone who offered to help.
