### ISSUE TITLE
Move stylesheets and js into separate files

### ISSUE THREAD

**Issue by yuryu** [GoogleCloudPlatform/gcping#56]
Can we move the stylesheets and js code into separate files (.css and .js) instead of having everything in index.html? I can make a PR if this makes sense. It will make future development a bit easier.

**Comment by enocom** [comment]
I think that's reasonable. One thing to consider is attaching fingerprints to the assets, such that changes immediate reach our uses. To me that implies introducing a better build tool for the frontend.

cc @saranshdhingra who's been thinking about this problem as well.

**Comment by yuryu** [comment]
Sorry I opened the PR before reading your comment. At the moment there is no CDN or cache control so I'm assuming it's safe, but yes, I'm also interested in introducing a build tool and potentially a framework too.

**Comment by saranshdhingra** [comment]
The 2 branches which are ahead of the main branch( one of them being https://github.com/GoogleCloudPlatform/gcping/tree/ui-with-maps-design-2) have this problem solved.

They aren't merged because we are experimenting with the UX a bit before changing the design for the users.
So, the change will essentially be nullified once we merge the other branch(_in fact if I am not wrong it will lead to conflicts on the index file_).

So, my suggestion is we close this, Sorry for the effort you put in :(

**Comment by enocom** [comment]
@saranshdhingra Could we try to merge some of these improvements one at a time separately from the UX changes? Otherwise, the UX changes will be blocking any changes to the frontend.

**Comment by yuryu** [comment]
I'll go ahead and merge this as it won't change behaviors and the existing work can continue independently.
